PROJECT = System

PROJECT_SRC     = \
                njGlobal_.src\
                njkm_.src\
                njMalloc.c\
                njMem_.src\
                njSystem_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc