PROJECT = Kamui

PROJECT_SRC     = \
                bgplane_kamui_lib_.src\
                dbgprint_kamui_lib_.src\
                dma_kamui_lib_.src\
                dummy_.src\
                fballoc_kamui_lib_.src\
                hwinit_kamui_lib_.src\
                inifile_kamui_lib_.src\
                internal_kamui_lib_.src\
                interupt_kamui_lib_.src\
                kmasm_kamui_lib_.src\
                kmcalbac_kamui_lib_.src\
                kmdevice_kamui_lib_.src\
                kmdirect_kamui_lib_.src\
                kmframe_kamui_lib_.src\
                kmglobal_kamui_lib_.src\
                kmimem_kamui_lib_.src\
                kmsrvice_kamui_lib_.src\
                kmsurfac_kamui_lib_.src\
                kmtex_kamui_lib_.src\
                kmutil_kmutil_lib_.src\
                kmvers_kamui_lib_.src\
                kmvertex_kamui_lib_.src\
                kmvtxbuf_kamui_lib_.src\
                kmvtxlst_kamui_lib_.src\
                memcpy8_.src\
                register_kamui_lib_.src\
                tactrl_kamui_lib_.src\
                video_kamui_lib_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc