PROJECT = Texture

PROJECT_SRC     = \
                njCheckTextureFormat_.src\
                njCreateTextureSurface.c\
                njGetTextureNumG.c\
                njInitCacheTexture_.src\
                njLoadCacheTextureNumG_.src\
                njLoadCacheTextureNum_.src\
                njLoadCacheTexture_.src\
                njLoadTextureLN_.src\
                njLoadTextureNum_.src\
                njLoadTexturePvmFile_.src\
                njLoadTextureReq_.src\
                njLoadTextureSetG_.src\
                njLoadTextureYUV420_.src\
                njPalette_.src\
                njReadRectangleTexturePart_.src\
                njReadTexturePartNumG_.src\
                njReadTexturePartNum_.src\
                njReadTexture_.src\
                njReleaseCacheTextureAll_.src\
                njReleaseCacheTextureNumG_.src\
                njReleaseCacheTextureNum_.src\
                njReleaseTextureAll_.src\
                njReleaseTextureNumG_.src\
                njReleaseTextureNum_.src\
                njReleaseTexture_.src\
                njReLoadRectangleTexturePart_.src\
                njReLoadTextureNumG_.src\
                njReLoadTextureNum_.src\
                njReLoadTexturePart_.src\
                njReLoadVQCodebookNum_.src\
                njSetTextureInfo.c\
                njSetTextureNumG_.src\
                njSetTextureParam_.src\
                njTexFile_.src\
                njTexinner_.src\
                njTexList_.src\
                njTexLoadLow_.src\
                njTexLoad_.src\
                njTexLow_.src\
                njTexMemCopy_.src\
                njTexpvr_.src\
                njTexStride_.src\
                njTextureGlobal_.src\
                njTexture.c\
                njTwiddledTexture_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc