PROJECT = View

PROJECT_SRC     = \
                njForwardCameraPosition_.src\
                njForwardViewAbsolute_.src\
                njForwardViewRelative_.src\
                njInitCamera_.src\
                njInitView_.src\
                njLookAtViewV_.src\
                njLookAtView_.src\
                njMultiViewMatrix_.src\
                njPitchCameraInterest_.src\
                njPointCamereInterest_.src\
                njReturn2BaseView_.src\
                njRollCameraInterest_.src\
                njRotateCameraPositionXYZ_.src\
                njRotateCameraPositionX_.src\
                njRotateCameraPositionY_.src\
                njRotateCameraPositionZ_.src\
                njRotateViewPosXAbsolute_.src\
                njRotateViewPosXRelative_.src\
                njRotateViewPosYAbsolute_.src\
                njRotateViewPosYRelative_.src\
                njRotateViewPosZAbsolute_.src\
                njRotateViewPosZRelative_.src\
                njRotateViewXAbsolute_.src\
                njRotateViewXRelative_.src\
                njRotateViewXYZAbsolute_.src\
                njRotateViewXYZRelative_.src\
                njRotateViewXYZ_.src\
                njRotateViewX_.src\
                njRotateViewYAbsolute_.src\
                njRotateViewYRelative_.src\
                njRotateViewY_.src\
                njRotateViewZAbsolute_.src\
                njRotateViewZRelative_.src\
                njRotateViewZ_.src\
                njSetAspect_.src\
                njSetBaseView_.src\
                njSetCameraAngle_.src\
                njSetCameraDepthZ_.src\
                njSetCamera_.src\
                njSetPerspective_.src\
                njSetScreenDist_.src\
                njSetScreen_.src\
                njSetView_.src\
                njTranslateCameraPosition_.src\
                njTranslateViewAbsolute_.src\
                njTranslateViewRelative_.src\
                njTranslateViewVAbsolute_.src\
                njTranslateViewVRelative_.src\
                njTranslateViewV_.src\
                njTranslateView_.src\
                njUnitViewMatrix_.src\
                njUnitViewVector_.src\
                njYawCameraInterest_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc