PROJECT =	Light

PROJECT_SRC	= \
		njCreateLight.ic\
		njDeleteAllLight.c\
		njDeleteLight.c\
		njlightalloff.c\
		njlightallon.c\
		njLightOff.c\
		njLightOn.c\
		njLightSystemInit.c\
		njLight_.src\
		njltmath_.src\
		njltsrcs2_.src\
		njLtSrcs3_.src\
		njltsrcs_.src\
		njMultiLightMatrix.c\
		njRotateLightXYZ.c\
		njRotateLightX.c\
		njRotateLightY.c\
		njRotateLightZ.c\
		njSetLightAlpha.c\
		njSetLightAngle_.src\
		njSetLightColor.c\
		njSetLightDirection2_.src\
		njSetLightDirection.c\
		njSetLightIntensity.c\
		njSetLightLocation.c\
		njSetLightRange_.src\
		njSetLight_.src\
		njSetUserLight.c\
		njTranslateLightV.c\
		njTranslateLight.c\
		njUnitLightMatrix.c

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc
