PROJECT = Motion

PROJECT_SRC     = \
                njCameraMotion_.src\
                njCellSpriteMotion_.src\
                njCnkMotCon_.src\
                njCnkMotInt_.src\
                njCnkMotionEM_.src\
                njCnkMotionE_.src\
                njCnkMotionS_.src\
                njCnkMotion_.src\
                njCnkMotLinkEM_.src\
                njCnkMotLinkE_.src\
                njCnkMotLinkSrc_.src\
                njCnkMotLinkS_.src\
                njCnkMotLink_.src\
                njCnkMotSrc_.src\
                njCnkShapeEM_.src\
                njCnkShapeE_.src\
                njCnkShapeInt_.src\
                njCnkShapeLinkEM_.src\
                njCnkShapeLinkE_.src\
                njCnkShapeLinkSrc_.src\
                njCnkShapeLinkS_.src\
                njCnkShapeLink_.src\
                njCnkShapeSrc_.src\
                njCnkShapeS_.src\
                njCnkShape_.src\
                njGetCameraMotion_.src\
                njGetLightMotion_.src\
                njGetMotion_.src\
                njLightMotion_.src\
                njMotExpand_.src\
                njMotIntOld_.src\
                njMotInt_.src\
                njMotionE_.src\
                njMotionF_.src\
                njMotionS_.src\
                njMotion_.src\
                njMotLinkE_.src\
                njMotLinkF_.src\
                njMotLinkSrc_.src\
                njMotLinkS_.src\
                njMotLink_.src\
                njMotSrc_.src\
                njPtclMotion_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc