PROJECT = Collision
PROJECT_SRC     = \
                njCheckBBox_.src\
                njCollisionCheckBB_.src\
                njCollisionCheckBC_.src\
                njCollisionCheckBS_.src\
                njCollisionCheckCC_.src\
                njCollisionCheckSC_.src\
                njCollisionCheckSS_.src\
                njGetBoxMinMax_.src\
                njGetCapsuleMinMax_.src\
                njGetPlaneNormal2_.src\
                njGetPlaneNormal_.src\
                njGetSphereMinMax_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc