PROJECT = Math

PROJECT_SRC     = \
                njAddMatrix_.src\
                njAddVector_.src\
                njBezier_.src\
                njCalcPoints_.src\
                njCalcPoint_.src\
                njCalcScreen_.src\
                njCalcVectors_.src\
                njCalcVector_.src\
                njCardinal_.src\
                njCheckOverlappedRect_.src\
                njClearMatrix_.src\
                njCombination_.src\
                njCosec_.src\
                njCos_.src\
                njCot_.src\
                njCubicBezier_.src\
                njDCalcPoint3D2_.src\
                njDetMatrix_.src\
                njDistanceL2L_.src\
                njDistanceL2PL_.src\
                njDistanceP2L_.src\
                njDistanceP2PL_.src\
                njDistanceP2P_.src\
                njDistancePL2PL_.src\
                njFraction_.src\
                njGetMatrix_.src\
                njGetTranslation_.src\
                njHermite_.src\
                njInitMatrix_.src\
                njInnerProduct_.src\
                njInvertMatrix_.src\
                njIsParalellL2L_.src\
                njIsParalellL2PL_.src\
                njIsParalellPL2PL_.src\
                njKochanek_.src\
                njLinear_.src\
                njMirror_.src\
                njMultiMatrix_.src\
                njOuterProduct_.src\
                njOverhauser_.src\
                njPopMatrixEx_.src\
                njPopMatrix_.src\
                njProject2_.src\
                njProjectScreen_.src\
                njProject_.src\
                njPushMatrixEx_.src\
                njPushMatrix_.src\
                njQuaternionEx_.src\
                njRandom_.src\
                njResMatrix_.src\
                njRotateEx_.src\
                njRotateXYZ_.src\
                njRotateX_.src\
                njRotateY_.src\
                njRotateZXY_.src\
                njRotateZ_.src\
                njRotate_.src\
                njRoundOff_.src\
                njRoundUp_.src\
                njScaleEx_.src\
                njScaleV_.src\
                njScale_.src\
                njScalor2_.src\
                njScalor_.src\
                njSec_.src\
                njSetMatrix_.src\
                njSinCosTbl_.src\
                njSin_.src\
                njSqrt_.src\
                njSubMatrix_.src\
                njSubVector_.src\
                njTan_.src\
                njTranslateEx_.src\
                njTranslateV_.src\
                njTranslate_.src\
                njTransposeMatrix_.src\
                njUnitMatrix_.src\
                njUnitRotPortion_.src\
                njUnitTransPortion_.src\
                njUnitVector_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc