PROJECT = Particle

PROJECT_SRC     = \
                njPtclModel.c\
                njPtclPolygon.ic\
                njPtclSprite.ic\
                njPtclStrip.ic\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc