PROJECT = Draw

PROJECT_SRC     = \
                debugvq_.src\
                njCellSprite_.src\
                njClip2D_.src\
                njClipZ_.src\
                njControl_.src\
                njDebug_.src\
                njDirectDrawClip_.src\
                njDirectDraw_.src\
                njDrawCircle2D_.src\
                njDrawLine2D_.src\
                njDrawLine3D_.src\
                njDrawPoint2D_.src\
                njDrawPoint3D_.src\
                njDrawPolygon2D_.src\
                njDrawPolygon3D_.src\
                njDrawPolygon3_.src\
                njDrawTexture3H_.src\
                njDrawTexture3_.src\
                njDrawTextureH_.src\
                njDrawTriangle2D_.src\
                njDrawTriangle3D_.src\
                njDraw_.src\
                njModelE_.src\
                njModelF_.src\
                njModelGlobal_.src\
                njModelS_.src\
                njModel_.src\
                njQuad_.src\
                njScroll_.src\
                njSprite_.src\
                njTri_Filled_.src\
                njTri_Filled_With_Tex_.src\
                njTri_Wired_.src\
                njTri_Wired_With_Tex_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc