PROJECT = ChunkEasy

PROJECT_SRC	= \
		njCnkEasyBumpLight_.src\
		njCnkEasyMultiLight_.src\
		njCnkEasyMultiPolygon2p_.src\
		njCnkEasyMultiPolygonClip2p_.src\
		njCnkEasyMultiPolygonClip_.src\
		njCnkEasyMultiPolygonNearClip2p_.src\
		njCnkEasyMultiPolygonNearClip_.src\
		njCnkEasyMultiPolygon_.src\
		njCnkEasyMultiTexture2p2_.src\
		njCnkEasyMultiTexture2p_.src\
		njCnkEasyMultiTextureClip2p2_.src\
		njCnkEasyMultiTextureClip2p_.src\
		njCnkEasyMultiTextureClip_.src\
		njCnkEasyMultiTextureNearClip2p2_.src\
		njCnkEasyMultiTextureNearClip2p_.src\
		njCnkEasyMultiTextureNearClip_.src\
		njCnkEasyMultiTexture_.src\
		njCnkEasyMultiVertexVND8DepthQueue_.src\
		njCnkEasyMultiVertexVND8_.src\
		njCnkEasyMultiVertexVNDepthQueue_.src\
		njCnkEasyMultiVertexVNNFDepthQueue_.src\
		njCnkEasyMultiVertexVNNF_.src\
		njCnkEasyMultiVertexVN_.src\
		njCnkEasyPolygon2p_.src\
		njCnkEasyPolygonClip2p_.src\
		njCnkEasyPolygonClip_.src\
		njCnkEasyPolygonNearClip2p_.src\
		njCnkEasyPolygon_.src\
		njCnkEasyTexture2p2_.src\
		njCnkEasyTexture2p_.src\
		njCnkEasyTextureBumpClip_.src\
		njCnkEasyTextureBump_.src\
		njCnkEasyTextureClip2p2_.src\
		njCnkEasyTextureClip2p_.src\
		njCnkEasyTextureClip_.src\
		njCnkEasyTextureNearClip2p2_.src\
		njCnkEasyTextureNearClip2p_.src\
		njCnkEasyTexture_.src\
		njCnkEasyVertexSHVN_.src\
		njCnkEasyVertexSHV_.src\
		njCnkEasyVertexV1_.src\
		njCnkEasyVertexVD8_.src\
		njCnkEasyVertexVI_.src\
		njCnkEasyVertexVN1_.src\
		njCnkEasyVertexVND8_.src\
		njCnkEasyVertexVNNF_.src\
		njCnkEasyVertexVNX1_.src\
		njCnkEasyVertexVNX_.src\
		njCnkEasyVertexVN_.src\
		njCnkEasyVertexV_.src\

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\..\Include
include ..\..\..\dc.inc