PROJECT =	Effects

PROJECT_SRC	= \
		njExecuteFade.c\
 		njFadeDisable.c\
 		njFadeEnable.c\
 		njFogDisable.c\
 		njFogEnable.c\
 		njGenerateFogDensity_.src\
 		njGenerateFogTable_.src\
 		njGenerateFogTable2_.src\
 		njGenerateFogTable3_.src\
 		njSetFadeColor.c\
 		njSetFogColor.c\
 		njSetFogDensity.c\
 		njSetFogTable.c

OPTIMIZE =      1

COMPILER =	SHC
GFXLIB =	
OUTPUT =	LIB

DEBUG  =	FALSE
LIST   =	TRUE

#this is stupid probably but i dont know how to do it any other way
DEF_INCLUDE	= ..\..\Include
include ..\..\dc.inc
